`timescale 1ns/1ps
`include "noc_defines.vh"

module hybrid_noc_v2
(
    input clk,
    input rst,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in0,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in1,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in2,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in3,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in4,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in5,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in6,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in7,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in8,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in9,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in10,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in11,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in12,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in13,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in14,
    input  [`PACKET_WIDTH-1:0] c0_local_packet_in15,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in0,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in1,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in2,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in3,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in4,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in5,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in6,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in7,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in8,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in9,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in10,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in11,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in12,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in13,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in14,
    input  [`PACKET_WIDTH-1:0] c1_local_packet_in15,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in0,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in1,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in2,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in3,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in4,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in5,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in6,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in7,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in8,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in9,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in10,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in11,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in12,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in13,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in14,
    input  [`PACKET_WIDTH-1:0] c2_local_packet_in15,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in0,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in1,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in2,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in3,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in4,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in5,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in6,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in7,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in8,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in9,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in10,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in11,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in12,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in13,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in14,
    input  [`PACKET_WIDTH-1:0] c3_local_packet_in15,
    input  c0_local_write0,
    input  c0_local_write1,
    input  c0_local_write2,
    input  c0_local_write3,
    input  c0_local_write4,
    input  c0_local_write5,
    input  c0_local_write6,
    input  c0_local_write7,
    input  c0_local_write8,
    input  c0_local_write9,
    input  c0_local_write10,
    input  c0_local_write11,
    input  c0_local_write12,
    input  c0_local_write13,
    input  c0_local_write14,
    input  c0_local_write15,
    input  c1_local_write0,
    input  c1_local_write1,
    input  c1_local_write2,
    input  c1_local_write3,
    input  c1_local_write4,
    input  c1_local_write5,
    input  c1_local_write6,
    input  c1_local_write7,
    input  c1_local_write8,
    input  c1_local_write9,
    input  c1_local_write10,
    input  c1_local_write11,
    input  c1_local_write12,
    input  c1_local_write13,
    input  c1_local_write14,
    input  c1_local_write15,
    input  c2_local_write0,
    input  c2_local_write1,
    input  c2_local_write2,
    input  c2_local_write3,
    input  c2_local_write4,
    input  c2_local_write5,
    input  c2_local_write6,
    input  c2_local_write7,
    input  c2_local_write8,
    input  c2_local_write9,
    input  c2_local_write10,
    input  c2_local_write11,
    input  c2_local_write12,
    input  c2_local_write13,
    input  c2_local_write14,
    input  c2_local_write15,
    input  c3_local_write0,
    input  c3_local_write1,
    input  c3_local_write2,
    input  c3_local_write3,
    input  c3_local_write4,
    input  c3_local_write5,
    input  c3_local_write6,
    input  c3_local_write7,
    input  c3_local_write8,
    input  c3_local_write9,
    input  c3_local_write10,
    input  c3_local_write11,
    input  c3_local_write12,
    input  c3_local_write13,
    input  c3_local_write14,
    input  c3_local_write15,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out0,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out1,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out2,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out3,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out4,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out5,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out6,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out7,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out8,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out9,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out10,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out11,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out12,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out13,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out14,
    output [`PACKET_WIDTH-1:0] c0_local_packet_out15,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out0,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out1,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out2,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out3,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out4,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out5,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out6,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out7,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out8,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out9,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out10,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out11,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out12,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out13,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out14,
    output [`PACKET_WIDTH-1:0] c1_local_packet_out15,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out0,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out1,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out2,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out3,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out4,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out5,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out6,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out7,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out8,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out9,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out10,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out11,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out12,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out13,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out14,
    output [`PACKET_WIDTH-1:0] c2_local_packet_out15,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out0,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out1,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out2,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out3,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out4,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out5,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out6,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out7,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out8,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out9,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out10,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out11,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out12,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out13,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out14,
    output [`PACKET_WIDTH-1:0] c3_local_packet_out15,
    output c0_local_valid0,
    output c0_local_valid1,
    output c0_local_valid2,
    output c0_local_valid3,
    output c0_local_valid4,
    output c0_local_valid5,
    output c0_local_valid6,
    output c0_local_valid7,
    output c0_local_valid8,
    output c0_local_valid9,
    output c0_local_valid10,
    output c0_local_valid11,
    output c0_local_valid12,
    output c0_local_valid13,
    output c0_local_valid14,
    output c0_local_valid15,
    output c1_local_valid0,
    output c1_local_valid1,
    output c1_local_valid2,
    output c1_local_valid3,
    output c1_local_valid4,
    output c1_local_valid5,
    output c1_local_valid6,
    output c1_local_valid7,
    output c1_local_valid8,
    output c1_local_valid9,
    output c1_local_valid10,
    output c1_local_valid11,
    output c1_local_valid12,
    output c1_local_valid13,
    output c1_local_valid14,
    output c1_local_valid15,
    output c2_local_valid0,
    output c2_local_valid1,
    output c2_local_valid2,
    output c2_local_valid3,
    output c2_local_valid4,
    output c2_local_valid5,
    output c2_local_valid6,
    output c2_local_valid7,
    output c2_local_valid8,
    output c2_local_valid9,
    output c2_local_valid10,
    output c2_local_valid11,
    output c2_local_valid12,
    output c2_local_valid13,
    output c2_local_valid14,
    output c2_local_valid15,
    output c3_local_valid0,
    output c3_local_valid1,
    output c3_local_valid2,
    output c3_local_valid3,
    output c3_local_valid4,
    output c3_local_valid5,
    output c3_local_valid6,
    output c3_local_valid7,
    output c3_local_valid8,
    output c3_local_valid9,
    output c3_local_valid10,
    output c3_local_valid11,
    output c3_local_valid12,
    output c3_local_valid13,
    output c3_local_valid14,
    output c3_local_valid15
);

    wire [`PACKET_WIDTH-1:0] c0_gateway_out;
    wire c0_gateway_valid;
    wire c0_gateway_full;
    wire [`PACKET_WIDTH-1:0] c0_gateway_in;
    wire c0_gateway_valid_in;
    wire c0_global_ready;
    wire [2:0] c0_route_direction;

    wire [`PACKET_WIDTH-1:0] c1_gateway_out;
    wire c1_gateway_valid;
    wire c1_gateway_full;
    wire [`PACKET_WIDTH-1:0] c1_gateway_in;
    wire c1_gateway_valid_in;
    wire c1_global_ready;
    wire [2:0] c1_route_direction;

    wire [`PACKET_WIDTH-1:0] c2_gateway_out;
    wire c2_gateway_valid;
    wire c2_gateway_full;
    wire [`PACKET_WIDTH-1:0] c2_gateway_in;
    wire c2_gateway_valid_in;
    wire c2_global_ready;
    wire [2:0] c2_route_direction;

    wire [`PACKET_WIDTH-1:0] c3_gateway_out;
    wire c3_gateway_valid;
    wire c3_gateway_full;
    wire [`PACKET_WIDTH-1:0] c3_gateway_in;
    wire c3_gateway_valid_in;
    wire c3_global_ready;
    wire [2:0] c3_route_direction;

    spidergon_routing ROUTE_C0
    (
        .current_gateway(2'd0),
        .dest_gateway(c0_gateway_out[`PACKET_WIDTH-1 -: `CLUSTER_BITS]),
        .direction(c0_route_direction)
    );

    spidergon_routing ROUTE_C1
    (
        .current_gateway(2'd1),
        .dest_gateway(c1_gateway_out[`PACKET_WIDTH-1 -: `CLUSTER_BITS]),
        .direction(c1_route_direction)
    );

    spidergon_routing ROUTE_C2
    (
        .current_gateway(2'd2),
        .dest_gateway(c2_gateway_out[`PACKET_WIDTH-1 -: `CLUSTER_BITS]),
        .direction(c2_route_direction)
    );

    spidergon_routing ROUTE_C3
    (
        .current_gateway(2'd3),
        .dest_gateway(c3_gateway_out[`PACKET_WIDTH-1 -: `CLUSTER_BITS]),
        .direction(c3_route_direction)
    );

    mesh_4x4 #(.CLUSTER_ID(2'd0)) C0_MESH
    (
        .clk(clk), .rst(rst),
        .local_packet_in0(c0_local_packet_in0),
        .local_packet_in1(c0_local_packet_in1),
        .local_packet_in2(c0_local_packet_in2),
        .local_packet_in3(c0_local_packet_in3),
        .local_packet_in4(c0_local_packet_in4),
        .local_packet_in5(c0_local_packet_in5),
        .local_packet_in6(c0_local_packet_in6),
        .local_packet_in7(c0_local_packet_in7),
        .local_packet_in8(c0_local_packet_in8),
        .local_packet_in9(c0_local_packet_in9),
        .local_packet_in10(c0_local_packet_in10),
        .local_packet_in11(c0_local_packet_in11),
        .local_packet_in12(c0_local_packet_in12),
        .local_packet_in13(c0_local_packet_in13),
        .local_packet_in14(c0_local_packet_in14),
        .local_packet_in15(c0_local_packet_in15),
        .local_write0(c0_local_write0),
        .local_write1(c0_local_write1),
        .local_write2(c0_local_write2),
        .local_write3(c0_local_write3),
        .local_write4(c0_local_write4),
        .local_write5(c0_local_write5),
        .local_write6(c0_local_write6),
        .local_write7(c0_local_write7),
        .local_write8(c0_local_write8),
        .local_write9(c0_local_write9),
        .local_write10(c0_local_write10),
        .local_write11(c0_local_write11),
        .local_write12(c0_local_write12),
        .local_write13(c0_local_write13),
        .local_write14(c0_local_write14),
        .local_write15(c0_local_write15),
        .local_packet_out0(c0_local_packet_out0),
        .local_packet_out1(c0_local_packet_out1),
        .local_packet_out2(c0_local_packet_out2),
        .local_packet_out3(c0_local_packet_out3),
        .local_packet_out4(c0_local_packet_out4),
        .local_packet_out5(c0_local_packet_out5),
        .local_packet_out6(c0_local_packet_out6),
        .local_packet_out7(c0_local_packet_out7),
        .local_packet_out8(c0_local_packet_out8),
        .local_packet_out9(c0_local_packet_out9),
        .local_packet_out10(c0_local_packet_out10),
        .local_packet_out11(c0_local_packet_out11),
        .local_packet_out12(c0_local_packet_out12),
        .local_packet_out13(c0_local_packet_out13),
        .local_packet_out14(c0_local_packet_out14),
        .local_packet_out15(c0_local_packet_out15),
        .local_valid0(c0_local_valid0),
        .local_valid1(c0_local_valid1),
        .local_valid2(c0_local_valid2),
        .local_valid3(c0_local_valid3),
        .local_valid4(c0_local_valid4),
        .local_valid5(c0_local_valid5),
        .local_valid6(c0_local_valid6),
        .local_valid7(c0_local_valid7),
        .local_valid8(c0_local_valid8),
        .local_valid9(c0_local_valid9),
        .local_valid10(c0_local_valid10),
        .local_valid11(c0_local_valid11),
        .local_valid12(c0_local_valid12),
        .local_valid13(c0_local_valid13),
        .local_valid14(c0_local_valid14),
        .local_valid15(c0_local_valid15),
        .gateway_packet_in(c0_gateway_in),
        .gateway_write(c0_gateway_valid_in),
        .gateway_busy(!c0_global_ready),
        .gateway_packet_out(c0_gateway_out),
        .gateway_valid(c0_gateway_valid),
        .gateway_full(c0_gateway_full)
    );

    mesh_4x4 #(.CLUSTER_ID(2'd1)) C1_MESH
    (
        .clk(clk), .rst(rst),
        .local_packet_in0(c1_local_packet_in0),
        .local_packet_in1(c1_local_packet_in1),
        .local_packet_in2(c1_local_packet_in2),
        .local_packet_in3(c1_local_packet_in3),
        .local_packet_in4(c1_local_packet_in4),
        .local_packet_in5(c1_local_packet_in5),
        .local_packet_in6(c1_local_packet_in6),
        .local_packet_in7(c1_local_packet_in7),
        .local_packet_in8(c1_local_packet_in8),
        .local_packet_in9(c1_local_packet_in9),
        .local_packet_in10(c1_local_packet_in10),
        .local_packet_in11(c1_local_packet_in11),
        .local_packet_in12(c1_local_packet_in12),
        .local_packet_in13(c1_local_packet_in13),
        .local_packet_in14(c1_local_packet_in14),
        .local_packet_in15(c1_local_packet_in15),
        .local_write0(c1_local_write0),
        .local_write1(c1_local_write1),
        .local_write2(c1_local_write2),
        .local_write3(c1_local_write3),
        .local_write4(c1_local_write4),
        .local_write5(c1_local_write5),
        .local_write6(c1_local_write6),
        .local_write7(c1_local_write7),
        .local_write8(c1_local_write8),
        .local_write9(c1_local_write9),
        .local_write10(c1_local_write10),
        .local_write11(c1_local_write11),
        .local_write12(c1_local_write12),
        .local_write13(c1_local_write13),
        .local_write14(c1_local_write14),
        .local_write15(c1_local_write15),
        .local_packet_out0(c1_local_packet_out0),
        .local_packet_out1(c1_local_packet_out1),
        .local_packet_out2(c1_local_packet_out2),
        .local_packet_out3(c1_local_packet_out3),
        .local_packet_out4(c1_local_packet_out4),
        .local_packet_out5(c1_local_packet_out5),
        .local_packet_out6(c1_local_packet_out6),
        .local_packet_out7(c1_local_packet_out7),
        .local_packet_out8(c1_local_packet_out8),
        .local_packet_out9(c1_local_packet_out9),
        .local_packet_out10(c1_local_packet_out10),
        .local_packet_out11(c1_local_packet_out11),
        .local_packet_out12(c1_local_packet_out12),
        .local_packet_out13(c1_local_packet_out13),
        .local_packet_out14(c1_local_packet_out14),
        .local_packet_out15(c1_local_packet_out15),
        .local_valid0(c1_local_valid0),
        .local_valid1(c1_local_valid1),
        .local_valid2(c1_local_valid2),
        .local_valid3(c1_local_valid3),
        .local_valid4(c1_local_valid4),
        .local_valid5(c1_local_valid5),
        .local_valid6(c1_local_valid6),
        .local_valid7(c1_local_valid7),
        .local_valid8(c1_local_valid8),
        .local_valid9(c1_local_valid9),
        .local_valid10(c1_local_valid10),
        .local_valid11(c1_local_valid11),
        .local_valid12(c1_local_valid12),
        .local_valid13(c1_local_valid13),
        .local_valid14(c1_local_valid14),
        .local_valid15(c1_local_valid15),
        .gateway_packet_in(c1_gateway_in),
        .gateway_write(c1_gateway_valid_in),
        .gateway_busy(!c1_global_ready),
        .gateway_packet_out(c1_gateway_out),
        .gateway_valid(c1_gateway_valid),
        .gateway_full(c1_gateway_full)
    );

    mesh_4x4 #(.CLUSTER_ID(2'd2)) C2_MESH
    (
        .clk(clk), .rst(rst),
        .local_packet_in0(c2_local_packet_in0),
        .local_packet_in1(c2_local_packet_in1),
        .local_packet_in2(c2_local_packet_in2),
        .local_packet_in3(c2_local_packet_in3),
        .local_packet_in4(c2_local_packet_in4),
        .local_packet_in5(c2_local_packet_in5),
        .local_packet_in6(c2_local_packet_in6),
        .local_packet_in7(c2_local_packet_in7),
        .local_packet_in8(c2_local_packet_in8),
        .local_packet_in9(c2_local_packet_in9),
        .local_packet_in10(c2_local_packet_in10),
        .local_packet_in11(c2_local_packet_in11),
        .local_packet_in12(c2_local_packet_in12),
        .local_packet_in13(c2_local_packet_in13),
        .local_packet_in14(c2_local_packet_in14),
        .local_packet_in15(c2_local_packet_in15),
        .local_write0(c2_local_write0),
        .local_write1(c2_local_write1),
        .local_write2(c2_local_write2),
        .local_write3(c2_local_write3),
        .local_write4(c2_local_write4),
        .local_write5(c2_local_write5),
        .local_write6(c2_local_write6),
        .local_write7(c2_local_write7),
        .local_write8(c2_local_write8),
        .local_write9(c2_local_write9),
        .local_write10(c2_local_write10),
        .local_write11(c2_local_write11),
        .local_write12(c2_local_write12),
        .local_write13(c2_local_write13),
        .local_write14(c2_local_write14),
        .local_write15(c2_local_write15),
        .local_packet_out0(c2_local_packet_out0),
        .local_packet_out1(c2_local_packet_out1),
        .local_packet_out2(c2_local_packet_out2),
        .local_packet_out3(c2_local_packet_out3),
        .local_packet_out4(c2_local_packet_out4),
        .local_packet_out5(c2_local_packet_out5),
        .local_packet_out6(c2_local_packet_out6),
        .local_packet_out7(c2_local_packet_out7),
        .local_packet_out8(c2_local_packet_out8),
        .local_packet_out9(c2_local_packet_out9),
        .local_packet_out10(c2_local_packet_out10),
        .local_packet_out11(c2_local_packet_out11),
        .local_packet_out12(c2_local_packet_out12),
        .local_packet_out13(c2_local_packet_out13),
        .local_packet_out14(c2_local_packet_out14),
        .local_packet_out15(c2_local_packet_out15),
        .local_valid0(c2_local_valid0),
        .local_valid1(c2_local_valid1),
        .local_valid2(c2_local_valid2),
        .local_valid3(c2_local_valid3),
        .local_valid4(c2_local_valid4),
        .local_valid5(c2_local_valid5),
        .local_valid6(c2_local_valid6),
        .local_valid7(c2_local_valid7),
        .local_valid8(c2_local_valid8),
        .local_valid9(c2_local_valid9),
        .local_valid10(c2_local_valid10),
        .local_valid11(c2_local_valid11),
        .local_valid12(c2_local_valid12),
        .local_valid13(c2_local_valid13),
        .local_valid14(c2_local_valid14),
        .local_valid15(c2_local_valid15),
        .gateway_packet_in(c2_gateway_in),
        .gateway_write(c2_gateway_valid_in),
        .gateway_busy(!c2_global_ready),
        .gateway_packet_out(c2_gateway_out),
        .gateway_valid(c2_gateway_valid),
        .gateway_full(c2_gateway_full)
    );

    mesh_4x4 #(.CLUSTER_ID(2'd3)) C3_MESH
    (
        .clk(clk), .rst(rst),
        .local_packet_in0(c3_local_packet_in0),
        .local_packet_in1(c3_local_packet_in1),
        .local_packet_in2(c3_local_packet_in2),
        .local_packet_in3(c3_local_packet_in3),
        .local_packet_in4(c3_local_packet_in4),
        .local_packet_in5(c3_local_packet_in5),
        .local_packet_in6(c3_local_packet_in6),
        .local_packet_in7(c3_local_packet_in7),
        .local_packet_in8(c3_local_packet_in8),
        .local_packet_in9(c3_local_packet_in9),
        .local_packet_in10(c3_local_packet_in10),
        .local_packet_in11(c3_local_packet_in11),
        .local_packet_in12(c3_local_packet_in12),
        .local_packet_in13(c3_local_packet_in13),
        .local_packet_in14(c3_local_packet_in14),
        .local_packet_in15(c3_local_packet_in15),
        .local_write0(c3_local_write0),
        .local_write1(c3_local_write1),
        .local_write2(c3_local_write2),
        .local_write3(c3_local_write3),
        .local_write4(c3_local_write4),
        .local_write5(c3_local_write5),
        .local_write6(c3_local_write6),
        .local_write7(c3_local_write7),
        .local_write8(c3_local_write8),
        .local_write9(c3_local_write9),
        .local_write10(c3_local_write10),
        .local_write11(c3_local_write11),
        .local_write12(c3_local_write12),
        .local_write13(c3_local_write13),
        .local_write14(c3_local_write14),
        .local_write15(c3_local_write15),
        .local_packet_out0(c3_local_packet_out0),
        .local_packet_out1(c3_local_packet_out1),
        .local_packet_out2(c3_local_packet_out2),
        .local_packet_out3(c3_local_packet_out3),
        .local_packet_out4(c3_local_packet_out4),
        .local_packet_out5(c3_local_packet_out5),
        .local_packet_out6(c3_local_packet_out6),
        .local_packet_out7(c3_local_packet_out7),
        .local_packet_out8(c3_local_packet_out8),
        .local_packet_out9(c3_local_packet_out9),
        .local_packet_out10(c3_local_packet_out10),
        .local_packet_out11(c3_local_packet_out11),
        .local_packet_out12(c3_local_packet_out12),
        .local_packet_out13(c3_local_packet_out13),
        .local_packet_out14(c3_local_packet_out14),
        .local_packet_out15(c3_local_packet_out15),
        .local_valid0(c3_local_valid0),
        .local_valid1(c3_local_valid1),
        .local_valid2(c3_local_valid2),
        .local_valid3(c3_local_valid3),
        .local_valid4(c3_local_valid4),
        .local_valid5(c3_local_valid5),
        .local_valid6(c3_local_valid6),
        .local_valid7(c3_local_valid7),
        .local_valid8(c3_local_valid8),
        .local_valid9(c3_local_valid9),
        .local_valid10(c3_local_valid10),
        .local_valid11(c3_local_valid11),
        .local_valid12(c3_local_valid12),
        .local_valid13(c3_local_valid13),
        .local_valid14(c3_local_valid14),
        .local_valid15(c3_local_valid15),
        .gateway_packet_in(c3_gateway_in),
        .gateway_write(c3_gateway_valid_in),
        .gateway_busy(!c3_global_ready),
        .gateway_packet_out(c3_gateway_out),
        .gateway_valid(c3_gateway_valid),
        .gateway_full(c3_gateway_full)
    );

    global_network_4cluster GLOBAL_NETWORK
    (
        .clk(clk), .rst(rst),
        .c0_route_direction(c0_route_direction),
        .c0_packet_in(c0_gateway_out),
        .c0_valid_in(c0_gateway_valid),
        .c0_ready_out(c0_global_ready),
        .c0_packet_out(c0_gateway_in),
        .c0_valid_out(c0_gateway_valid_in),
        .c0_ready_in(!c0_gateway_full),
        .c1_route_direction(c1_route_direction),
        .c1_packet_in(c1_gateway_out),
        .c1_valid_in(c1_gateway_valid),
        .c1_ready_out(c1_global_ready),
        .c1_packet_out(c1_gateway_in),
        .c1_valid_out(c1_gateway_valid_in),
        .c1_ready_in(!c1_gateway_full),
        .c2_route_direction(c2_route_direction),
        .c2_packet_in(c2_gateway_out),
        .c2_valid_in(c2_gateway_valid),
        .c2_ready_out(c2_global_ready),
        .c2_packet_out(c2_gateway_in),
        .c2_valid_out(c2_gateway_valid_in),
        .c2_ready_in(!c2_gateway_full),
        .c3_route_direction(c3_route_direction),
        .c3_packet_in(c3_gateway_out),
        .c3_valid_in(c3_gateway_valid),
        .c3_ready_out(c3_global_ready),
        .c3_packet_out(c3_gateway_in),
        .c3_valid_out(c3_gateway_valid_in),
        .c3_ready_in(!c3_gateway_full)
    );

endmodule
