`timescale 1ns/1ps
`include "noc_defines.vh"

module mesh_4x4 #(
    parameter [1:0] CLUSTER_ID = 2'd0
)
(
    input clk,
    input rst,

    input  [`PACKET_WIDTH-1:0] local_packet_in0,
    input  [`PACKET_WIDTH-1:0] local_packet_in1,
    input  [`PACKET_WIDTH-1:0] local_packet_in2,
    input  [`PACKET_WIDTH-1:0] local_packet_in3,
    input  [`PACKET_WIDTH-1:0] local_packet_in4,
    input  [`PACKET_WIDTH-1:0] local_packet_in5,
    input  [`PACKET_WIDTH-1:0] local_packet_in6,
    input  [`PACKET_WIDTH-1:0] local_packet_in7,
    input  [`PACKET_WIDTH-1:0] local_packet_in8,
    input  [`PACKET_WIDTH-1:0] local_packet_in9,
    input  [`PACKET_WIDTH-1:0] local_packet_in10,
    input  [`PACKET_WIDTH-1:0] local_packet_in11,
    input  [`PACKET_WIDTH-1:0] local_packet_in12,
    input  [`PACKET_WIDTH-1:0] local_packet_in13,
    input  [`PACKET_WIDTH-1:0] local_packet_in14,
    input  [`PACKET_WIDTH-1:0] local_packet_in15,
    input  local_write0,
    input  local_write1,
    input  local_write2,
    input  local_write3,
    input  local_write4,
    input  local_write5,
    input  local_write6,
    input  local_write7,
    input  local_write8,
    input  local_write9,
    input  local_write10,
    input  local_write11,
    input  local_write12,
    input  local_write13,
    input  local_write14,
    input  local_write15,
    output [`PACKET_WIDTH-1:0] local_packet_out0,
    output [`PACKET_WIDTH-1:0] local_packet_out1,
    output [`PACKET_WIDTH-1:0] local_packet_out2,
    output [`PACKET_WIDTH-1:0] local_packet_out3,
    output [`PACKET_WIDTH-1:0] local_packet_out4,
    output [`PACKET_WIDTH-1:0] local_packet_out5,
    output [`PACKET_WIDTH-1:0] local_packet_out6,
    output [`PACKET_WIDTH-1:0] local_packet_out7,
    output [`PACKET_WIDTH-1:0] local_packet_out8,
    output [`PACKET_WIDTH-1:0] local_packet_out9,
    output [`PACKET_WIDTH-1:0] local_packet_out10,
    output [`PACKET_WIDTH-1:0] local_packet_out11,
    output [`PACKET_WIDTH-1:0] local_packet_out12,
    output [`PACKET_WIDTH-1:0] local_packet_out13,
    output [`PACKET_WIDTH-1:0] local_packet_out14,
    output [`PACKET_WIDTH-1:0] local_packet_out15,
    output local_valid0,
    output local_valid1,
    output local_valid2,
    output local_valid3,
    output local_valid4,
    output local_valid5,
    output local_valid6,
    output local_valid7,
    output local_valid8,
    output local_valid9,
    output local_valid10,
    output local_valid11,
    output local_valid12,
    output local_valid13,
    output local_valid14,
    output local_valid15,
    input  [`PACKET_WIDTH-1:0] gateway_packet_in,
    input  gateway_write,
    input  gateway_busy,
    output [`PACKET_WIDTH-1:0] gateway_packet_out,
    output gateway_valid,
    output gateway_full
);

    // 4x4 coordinates:
    // index = row*4 + col
    // R0  R1  R2  R3
    // R4  R5  R6  R7
    // R8  R9  R10 R11
    // R12 R13 R14 R15

    wire [`PACKET_WIDTH-1:0] north_pkt [0:15];
    wire [`PACKET_WIDTH-1:0] south_pkt [0:15];
    wire [`PACKET_WIDTH-1:0] east_pkt  [0:15];
    wire [`PACKET_WIDTH-1:0] west_pkt  [0:15];

    wire north_valid [0:15];
    wire south_valid [0:15];
    wire east_valid  [0:15];
    wire west_valid  [0:15];

    wire north_full [0:15];
    wire south_full [0:15];
    wire east_full  [0:15];
    wire west_full  [0:15];

    wire unused_local_full [0:15];
    wire [`PACKET_WIDTH-1:0] unused_packet [0:15];

    // R0 = (0,0)
    router R0
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in0),
        .north_packet_in({`PACKET_WIDTH{1'b0}}),
        .south_packet_in(north_pkt[4]),
        .east_packet_in(west_pkt[1]),
        .west_packet_in({`PACKET_WIDTH{1'b0}}),
        .gateway_packet_in(gateway_packet_in),
        .local_write(local_write0),
        .north_write(1'b0),
        .south_write(north_valid[4]),
        .east_write(west_valid[1]),
        .west_write(1'b0),
        .gateway_write(gateway_write),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd0),
        .my_col(2'd0),
        .local_busy(1'b0),
        .north_busy(1'b0),
        .south_busy(north_full[4]),
        .east_busy(west_full[1]),
        .west_busy(1'b0),
        .gateway_busy(gateway_busy),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out0),
        .north_packet_out(north_pkt[0]),
        .south_packet_out(south_pkt[0]),
        .east_packet_out(east_pkt[0]),
        .west_packet_out(west_pkt[0]),
        .gateway_packet_out(gateway_packet_out),
        .local_valid(local_valid0),
        .north_valid(north_valid[0]),
        .south_valid(south_valid[0]),
        .east_valid(east_valid[0]),
        .west_valid(west_valid[0]),
        .gateway_valid(gateway_valid),
        .local_full(unused_local_full[0]),
        .north_full(north_full[0]),
        .south_full(south_full[0]),
        .east_full(east_full[0]),
        .west_full(west_full[0]),
        .gateway_full(gateway_full)
    );

    // R1 = (0,1)
    router R1
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in1),
        .north_packet_in({`PACKET_WIDTH{1'b0}}),
        .south_packet_in(north_pkt[5]),
        .east_packet_in(west_pkt[2]),
        .west_packet_in(east_pkt[0]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write1),
        .north_write(1'b0),
        .south_write(north_valid[5]),
        .east_write(west_valid[2]),
        .west_write(east_valid[0]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd0),
        .my_col(2'd1),
        .local_busy(1'b0),
        .north_busy(1'b0),
        .south_busy(north_full[5]),
        .east_busy(west_full[2]),
        .west_busy(east_full[0]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out1),
        .north_packet_out(north_pkt[1]),
        .south_packet_out(south_pkt[1]),
        .east_packet_out(east_pkt[1]),
        .west_packet_out(west_pkt[1]),
        .gateway_packet_out(unused_packet[1]),
        .local_valid(local_valid1),
        .north_valid(north_valid[1]),
        .south_valid(south_valid[1]),
        .east_valid(east_valid[1]),
        .west_valid(west_valid[1]),
        .gateway_valid(),
        .local_full(unused_local_full[1]),
        .north_full(north_full[1]),
        .south_full(south_full[1]),
        .east_full(east_full[1]),
        .west_full(west_full[1]),
        .gateway_full()
    );

    // R2 = (0,2)
    router R2
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in2),
        .north_packet_in({`PACKET_WIDTH{1'b0}}),
        .south_packet_in(north_pkt[6]),
        .east_packet_in(west_pkt[3]),
        .west_packet_in(east_pkt[1]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write2),
        .north_write(1'b0),
        .south_write(north_valid[6]),
        .east_write(west_valid[3]),
        .west_write(east_valid[1]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd0),
        .my_col(2'd2),
        .local_busy(1'b0),
        .north_busy(1'b0),
        .south_busy(north_full[6]),
        .east_busy(west_full[3]),
        .west_busy(east_full[1]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out2),
        .north_packet_out(north_pkt[2]),
        .south_packet_out(south_pkt[2]),
        .east_packet_out(east_pkt[2]),
        .west_packet_out(west_pkt[2]),
        .gateway_packet_out(unused_packet[2]),
        .local_valid(local_valid2),
        .north_valid(north_valid[2]),
        .south_valid(south_valid[2]),
        .east_valid(east_valid[2]),
        .west_valid(west_valid[2]),
        .gateway_valid(),
        .local_full(unused_local_full[2]),
        .north_full(north_full[2]),
        .south_full(south_full[2]),
        .east_full(east_full[2]),
        .west_full(west_full[2]),
        .gateway_full()
    );

    // R3 = (0,3)
    router R3
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in3),
        .north_packet_in({`PACKET_WIDTH{1'b0}}),
        .south_packet_in(north_pkt[7]),
        .east_packet_in({`PACKET_WIDTH{1'b0}}),
        .west_packet_in(east_pkt[2]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write3),
        .north_write(1'b0),
        .south_write(north_valid[7]),
        .east_write(1'b0),
        .west_write(east_valid[2]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd0),
        .my_col(2'd3),
        .local_busy(1'b0),
        .north_busy(1'b0),
        .south_busy(north_full[7]),
        .east_busy(1'b0),
        .west_busy(east_full[2]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out3),
        .north_packet_out(north_pkt[3]),
        .south_packet_out(south_pkt[3]),
        .east_packet_out(east_pkt[3]),
        .west_packet_out(west_pkt[3]),
        .gateway_packet_out(unused_packet[3]),
        .local_valid(local_valid3),
        .north_valid(north_valid[3]),
        .south_valid(south_valid[3]),
        .east_valid(east_valid[3]),
        .west_valid(west_valid[3]),
        .gateway_valid(),
        .local_full(unused_local_full[3]),
        .north_full(north_full[3]),
        .south_full(south_full[3]),
        .east_full(east_full[3]),
        .west_full(west_full[3]),
        .gateway_full()
    );

    // R4 = (1,0)
    router R4
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in4),
        .north_packet_in(south_pkt[0]),
        .south_packet_in(north_pkt[8]),
        .east_packet_in(west_pkt[5]),
        .west_packet_in({`PACKET_WIDTH{1'b0}}),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write4),
        .north_write(south_valid[0]),
        .south_write(north_valid[8]),
        .east_write(west_valid[5]),
        .west_write(1'b0),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd1),
        .my_col(2'd0),
        .local_busy(1'b0),
        .north_busy(south_full[0]),
        .south_busy(north_full[8]),
        .east_busy(west_full[5]),
        .west_busy(1'b0),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out4),
        .north_packet_out(north_pkt[4]),
        .south_packet_out(south_pkt[4]),
        .east_packet_out(east_pkt[4]),
        .west_packet_out(west_pkt[4]),
        .gateway_packet_out(unused_packet[4]),
        .local_valid(local_valid4),
        .north_valid(north_valid[4]),
        .south_valid(south_valid[4]),
        .east_valid(east_valid[4]),
        .west_valid(west_valid[4]),
        .gateway_valid(),
        .local_full(unused_local_full[4]),
        .north_full(north_full[4]),
        .south_full(south_full[4]),
        .east_full(east_full[4]),
        .west_full(west_full[4]),
        .gateway_full()
    );

    // R5 = (1,1)
    router R5
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in5),
        .north_packet_in(south_pkt[1]),
        .south_packet_in(north_pkt[9]),
        .east_packet_in(west_pkt[6]),
        .west_packet_in(east_pkt[4]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write5),
        .north_write(south_valid[1]),
        .south_write(north_valid[9]),
        .east_write(west_valid[6]),
        .west_write(east_valid[4]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd1),
        .my_col(2'd1),
        .local_busy(1'b0),
        .north_busy(south_full[1]),
        .south_busy(north_full[9]),
        .east_busy(west_full[6]),
        .west_busy(east_full[4]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out5),
        .north_packet_out(north_pkt[5]),
        .south_packet_out(south_pkt[5]),
        .east_packet_out(east_pkt[5]),
        .west_packet_out(west_pkt[5]),
        .gateway_packet_out(unused_packet[5]),
        .local_valid(local_valid5),
        .north_valid(north_valid[5]),
        .south_valid(south_valid[5]),
        .east_valid(east_valid[5]),
        .west_valid(west_valid[5]),
        .gateway_valid(),
        .local_full(unused_local_full[5]),
        .north_full(north_full[5]),
        .south_full(south_full[5]),
        .east_full(east_full[5]),
        .west_full(west_full[5]),
        .gateway_full()
    );

    // R6 = (1,2)
    router R6
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in6),
        .north_packet_in(south_pkt[2]),
        .south_packet_in(north_pkt[10]),
        .east_packet_in(west_pkt[7]),
        .west_packet_in(east_pkt[5]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write6),
        .north_write(south_valid[2]),
        .south_write(north_valid[10]),
        .east_write(west_valid[7]),
        .west_write(east_valid[5]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd1),
        .my_col(2'd2),
        .local_busy(1'b0),
        .north_busy(south_full[2]),
        .south_busy(north_full[10]),
        .east_busy(west_full[7]),
        .west_busy(east_full[5]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out6),
        .north_packet_out(north_pkt[6]),
        .south_packet_out(south_pkt[6]),
        .east_packet_out(east_pkt[6]),
        .west_packet_out(west_pkt[6]),
        .gateway_packet_out(unused_packet[6]),
        .local_valid(local_valid6),
        .north_valid(north_valid[6]),
        .south_valid(south_valid[6]),
        .east_valid(east_valid[6]),
        .west_valid(west_valid[6]),
        .gateway_valid(),
        .local_full(unused_local_full[6]),
        .north_full(north_full[6]),
        .south_full(south_full[6]),
        .east_full(east_full[6]),
        .west_full(west_full[6]),
        .gateway_full()
    );

    // R7 = (1,3)
    router R7
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in7),
        .north_packet_in(south_pkt[3]),
        .south_packet_in(north_pkt[11]),
        .east_packet_in({`PACKET_WIDTH{1'b0}}),
        .west_packet_in(east_pkt[6]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write7),
        .north_write(south_valid[3]),
        .south_write(north_valid[11]),
        .east_write(1'b0),
        .west_write(east_valid[6]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd1),
        .my_col(2'd3),
        .local_busy(1'b0),
        .north_busy(south_full[3]),
        .south_busy(north_full[11]),
        .east_busy(1'b0),
        .west_busy(east_full[6]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out7),
        .north_packet_out(north_pkt[7]),
        .south_packet_out(south_pkt[7]),
        .east_packet_out(east_pkt[7]),
        .west_packet_out(west_pkt[7]),
        .gateway_packet_out(unused_packet[7]),
        .local_valid(local_valid7),
        .north_valid(north_valid[7]),
        .south_valid(south_valid[7]),
        .east_valid(east_valid[7]),
        .west_valid(west_valid[7]),
        .gateway_valid(),
        .local_full(unused_local_full[7]),
        .north_full(north_full[7]),
        .south_full(south_full[7]),
        .east_full(east_full[7]),
        .west_full(west_full[7]),
        .gateway_full()
    );

    // R8 = (2,0)
    router R8
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in8),
        .north_packet_in(south_pkt[4]),
        .south_packet_in(north_pkt[12]),
        .east_packet_in(west_pkt[9]),
        .west_packet_in({`PACKET_WIDTH{1'b0}}),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write8),
        .north_write(south_valid[4]),
        .south_write(north_valid[12]),
        .east_write(west_valid[9]),
        .west_write(1'b0),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd2),
        .my_col(2'd0),
        .local_busy(1'b0),
        .north_busy(south_full[4]),
        .south_busy(north_full[12]),
        .east_busy(west_full[9]),
        .west_busy(1'b0),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out8),
        .north_packet_out(north_pkt[8]),
        .south_packet_out(south_pkt[8]),
        .east_packet_out(east_pkt[8]),
        .west_packet_out(west_pkt[8]),
        .gateway_packet_out(unused_packet[8]),
        .local_valid(local_valid8),
        .north_valid(north_valid[8]),
        .south_valid(south_valid[8]),
        .east_valid(east_valid[8]),
        .west_valid(west_valid[8]),
        .gateway_valid(),
        .local_full(unused_local_full[8]),
        .north_full(north_full[8]),
        .south_full(south_full[8]),
        .east_full(east_full[8]),
        .west_full(west_full[8]),
        .gateway_full()
    );

    // R9 = (2,1)
    router R9
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in9),
        .north_packet_in(south_pkt[5]),
        .south_packet_in(north_pkt[13]),
        .east_packet_in(west_pkt[10]),
        .west_packet_in(east_pkt[8]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write9),
        .north_write(south_valid[5]),
        .south_write(north_valid[13]),
        .east_write(west_valid[10]),
        .west_write(east_valid[8]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd2),
        .my_col(2'd1),
        .local_busy(1'b0),
        .north_busy(south_full[5]),
        .south_busy(north_full[13]),
        .east_busy(west_full[10]),
        .west_busy(east_full[8]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out9),
        .north_packet_out(north_pkt[9]),
        .south_packet_out(south_pkt[9]),
        .east_packet_out(east_pkt[9]),
        .west_packet_out(west_pkt[9]),
        .gateway_packet_out(unused_packet[9]),
        .local_valid(local_valid9),
        .north_valid(north_valid[9]),
        .south_valid(south_valid[9]),
        .east_valid(east_valid[9]),
        .west_valid(west_valid[9]),
        .gateway_valid(),
        .local_full(unused_local_full[9]),
        .north_full(north_full[9]),
        .south_full(south_full[9]),
        .east_full(east_full[9]),
        .west_full(west_full[9]),
        .gateway_full()
    );

    // R10 = (2,2)
    router R10
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in10),
        .north_packet_in(south_pkt[6]),
        .south_packet_in(north_pkt[14]),
        .east_packet_in(west_pkt[11]),
        .west_packet_in(east_pkt[9]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write10),
        .north_write(south_valid[6]),
        .south_write(north_valid[14]),
        .east_write(west_valid[11]),
        .west_write(east_valid[9]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd2),
        .my_col(2'd2),
        .local_busy(1'b0),
        .north_busy(south_full[6]),
        .south_busy(north_full[14]),
        .east_busy(west_full[11]),
        .west_busy(east_full[9]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out10),
        .north_packet_out(north_pkt[10]),
        .south_packet_out(south_pkt[10]),
        .east_packet_out(east_pkt[10]),
        .west_packet_out(west_pkt[10]),
        .gateway_packet_out(unused_packet[10]),
        .local_valid(local_valid10),
        .north_valid(north_valid[10]),
        .south_valid(south_valid[10]),
        .east_valid(east_valid[10]),
        .west_valid(west_valid[10]),
        .gateway_valid(),
        .local_full(unused_local_full[10]),
        .north_full(north_full[10]),
        .south_full(south_full[10]),
        .east_full(east_full[10]),
        .west_full(west_full[10]),
        .gateway_full()
    );

    // R11 = (2,3)
    router R11
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in11),
        .north_packet_in(south_pkt[7]),
        .south_packet_in(north_pkt[15]),
        .east_packet_in({`PACKET_WIDTH{1'b0}}),
        .west_packet_in(east_pkt[10]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write11),
        .north_write(south_valid[7]),
        .south_write(north_valid[15]),
        .east_write(1'b0),
        .west_write(east_valid[10]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd2),
        .my_col(2'd3),
        .local_busy(1'b0),
        .north_busy(south_full[7]),
        .south_busy(north_full[15]),
        .east_busy(1'b0),
        .west_busy(east_full[10]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out11),
        .north_packet_out(north_pkt[11]),
        .south_packet_out(south_pkt[11]),
        .east_packet_out(east_pkt[11]),
        .west_packet_out(west_pkt[11]),
        .gateway_packet_out(unused_packet[11]),
        .local_valid(local_valid11),
        .north_valid(north_valid[11]),
        .south_valid(south_valid[11]),
        .east_valid(east_valid[11]),
        .west_valid(west_valid[11]),
        .gateway_valid(),
        .local_full(unused_local_full[11]),
        .north_full(north_full[11]),
        .south_full(south_full[11]),
        .east_full(east_full[11]),
        .west_full(west_full[11]),
        .gateway_full()
    );

    // R12 = (3,0)
    router R12
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in12),
        .north_packet_in(south_pkt[8]),
        .south_packet_in({`PACKET_WIDTH{1'b0}}),
        .east_packet_in(west_pkt[13]),
        .west_packet_in({`PACKET_WIDTH{1'b0}}),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write12),
        .north_write(south_valid[8]),
        .south_write(1'b0),
        .east_write(west_valid[13]),
        .west_write(1'b0),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd3),
        .my_col(2'd0),
        .local_busy(1'b0),
        .north_busy(south_full[8]),
        .south_busy(1'b0),
        .east_busy(west_full[13]),
        .west_busy(1'b0),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out12),
        .north_packet_out(north_pkt[12]),
        .south_packet_out(south_pkt[12]),
        .east_packet_out(east_pkt[12]),
        .west_packet_out(west_pkt[12]),
        .gateway_packet_out(unused_packet[12]),
        .local_valid(local_valid12),
        .north_valid(north_valid[12]),
        .south_valid(south_valid[12]),
        .east_valid(east_valid[12]),
        .west_valid(west_valid[12]),
        .gateway_valid(),
        .local_full(unused_local_full[12]),
        .north_full(north_full[12]),
        .south_full(south_full[12]),
        .east_full(east_full[12]),
        .west_full(west_full[12]),
        .gateway_full()
    );

    // R13 = (3,1)
    router R13
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in13),
        .north_packet_in(south_pkt[9]),
        .south_packet_in({`PACKET_WIDTH{1'b0}}),
        .east_packet_in(west_pkt[14]),
        .west_packet_in(east_pkt[12]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write13),
        .north_write(south_valid[9]),
        .south_write(1'b0),
        .east_write(west_valid[14]),
        .west_write(east_valid[12]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd3),
        .my_col(2'd1),
        .local_busy(1'b0),
        .north_busy(south_full[9]),
        .south_busy(1'b0),
        .east_busy(west_full[14]),
        .west_busy(east_full[12]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out13),
        .north_packet_out(north_pkt[13]),
        .south_packet_out(south_pkt[13]),
        .east_packet_out(east_pkt[13]),
        .west_packet_out(west_pkt[13]),
        .gateway_packet_out(unused_packet[13]),
        .local_valid(local_valid13),
        .north_valid(north_valid[13]),
        .south_valid(south_valid[13]),
        .east_valid(east_valid[13]),
        .west_valid(west_valid[13]),
        .gateway_valid(),
        .local_full(unused_local_full[13]),
        .north_full(north_full[13]),
        .south_full(south_full[13]),
        .east_full(east_full[13]),
        .west_full(west_full[13]),
        .gateway_full()
    );

    // R14 = (3,2)
    router R14
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in14),
        .north_packet_in(south_pkt[10]),
        .south_packet_in({`PACKET_WIDTH{1'b0}}),
        .east_packet_in(west_pkt[15]),
        .west_packet_in(east_pkt[13]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write14),
        .north_write(south_valid[10]),
        .south_write(1'b0),
        .east_write(west_valid[15]),
        .west_write(east_valid[13]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd3),
        .my_col(2'd2),
        .local_busy(1'b0),
        .north_busy(south_full[10]),
        .south_busy(1'b0),
        .east_busy(west_full[15]),
        .west_busy(east_full[13]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out14),
        .north_packet_out(north_pkt[14]),
        .south_packet_out(south_pkt[14]),
        .east_packet_out(east_pkt[14]),
        .west_packet_out(west_pkt[14]),
        .gateway_packet_out(unused_packet[14]),
        .local_valid(local_valid14),
        .north_valid(north_valid[14]),
        .south_valid(south_valid[14]),
        .east_valid(east_valid[14]),
        .west_valid(west_valid[14]),
        .gateway_valid(),
        .local_full(unused_local_full[14]),
        .north_full(north_full[14]),
        .south_full(south_full[14]),
        .east_full(east_full[14]),
        .west_full(west_full[14]),
        .gateway_full()
    );

    // R15 = (3,3)
    router R15
    (
        .clk(clk),
        .rst(rst),
        .local_packet_in(local_packet_in15),
        .north_packet_in(south_pkt[11]),
        .south_packet_in({`PACKET_WIDTH{1'b0}}),
        .east_packet_in({`PACKET_WIDTH{1'b0}}),
        .west_packet_in(east_pkt[14]),
        .gateway_packet_in({`PACKET_WIDTH{1'b0}}),
        .local_write(local_write15),
        .north_write(south_valid[11]),
        .south_write(1'b0),
        .east_write(1'b0),
        .west_write(east_valid[14]),
        .gateway_write(1'b0),
        .my_cluster(CLUSTER_ID),
        .my_row(2'd3),
        .my_col(2'd3),
        .local_busy(1'b0),
        .north_busy(south_full[11]),
        .south_busy(1'b0),
        .east_busy(1'b0),
        .west_busy(east_full[14]),
        .gateway_busy(1'b0),
        .local_ready(1'b1),
        .north_ready(1'b1),
        .south_ready(1'b1),
        .east_ready(1'b1),
        .west_ready(1'b1),
        .gateway_ready(1'b1),
        .local_packet_out(local_packet_out15),
        .north_packet_out(north_pkt[15]),
        .south_packet_out(south_pkt[15]),
        .east_packet_out(east_pkt[15]),
        .west_packet_out(west_pkt[15]),
        .gateway_packet_out(unused_packet[15]),
        .local_valid(local_valid15),
        .north_valid(north_valid[15]),
        .south_valid(south_valid[15]),
        .east_valid(east_valid[15]),
        .west_valid(west_valid[15]),
        .gateway_valid(),
        .local_full(unused_local_full[15]),
        .north_full(north_full[15]),
        .south_full(south_full[15]),
        .east_full(east_full[15]),
        .west_full(west_full[15]),
        .gateway_full()
    );

endmodule
